### ISSUE TITLE
Vulnerability in express-1.0.3.tgz (Root Library) > ejs-2.7.4.tgz (Vulnerable Library).

### ISSUE THREAD

**Issue by PraveenkumarD2004** [cislrpi/express#3]
**Describe the bug:**
We are getting vulnerability error in @cisl/express-1.0.3 version.

**Below is the dependency tree:**
@cisl/express-1.0.3.tgz (Root Library)
❌ ejs-2.7.4.tgz (Vulnerable Library)

**Expected behavior**
The @cisl/express should not be having any dependency on vulnerable components.

**Actual behavior**
The dependent package ejs-2.7.4 refers to be vulnerable components, as per the author the ejs-3.1.6 has the fix for the same.

**Comment by MasterOdin** [comment]
Thanks for reporting. This has been fixed in 605752d9e111f5979d9441e69ce380da5a274a75, and was included in v1.0.4 release.
